site_name: Hydro
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: astral-light
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: astral-dark
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
repo_url: https://github.com/sapph2c/exifool
repo_name: hydro
site_author: sapph2c 
site_url: https://docs.sapph2c.dev/hydro/
site_description: A MD5 hash cracker written in Python.
use_directory_urls: false
plugins:
  - search
extra_css:
  - stylesheets/extra.css
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - License: license.md

markdown_extensions:
  - admonition
  - codehilite
